default: &default
  adapter: postgresql
  encoding: unicode
  # username: tuta
  # password: rey
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rowasco_development

test:
  <<: *default
  database: rowasco_test

production:
  <<: *default
  database: rowasco_production
  username: rowasco
  password: <%= ENV["ROWASCO_DATABASE_PASSWORD"] %>
